# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/barapp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "update" met à jour le schéma de la base de données automatiquement d'après nos entités (Pratique en développement)
spring.jpa.hibernate.ddl-auto=create
# Affiche les requêtes SQL générées dans la console
spring.jpa.show-sql=true
